#!/usr/bin/env python3
"""Builds the README feature icons in docs/assets/icons/ from the Lucide icons Fuse already ships.

Usage (any working directory, Python 3 standard library only):
    python3 docs/assets/icons/source/build.py                 # writes ../*.svg and ../line/*.svg
    python3 docs/assets/icons/source/build.py --preview DIR   # also writes DIR/preview.html
    pip install playwright && python3 docs/assets/icons/source/build.py --preview DIR --png [--chromium PATH]
                                                              # and renders it on both GitHub themes

The path data is read from FuseIcons.kt (generated by tools/icons/generate_icons.py from Lucide, ISC),
so these icons are exactly the ones the app draws. Two sets are written:

- <name>.svg, 48 x 48: the icon in the Fuse accent on an ink squircle tile, lit like a focused tile in
  the app (a warm room glow, a light edge along the top, a soft glow under the strokes). The tile is
  self-contained, so one file reads on GitHub's light (#ffffff) and dark (#0d1117) backgrounds.
- line/<name>.svg, 24 x 24: the bare line icon in one warm orange (#F0582C, the colour of the
  one-colour Fuse mark) that keeps at least 3:1 contrast on both GitHub backgrounds.

Colours are the Fuse theme preset (ui/designsystem, theme/ThemePresets.kt): background #07080B,
surfaceRaised #1A1D25, accent #FF6A3D.
"""
import argparse
import importlib.util
import math
import os
import re
import sys

sys.dont_write_bytecode = True   # importing tools/icons/generate_icons.py must not leave a __pycache__ in the repo

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..'))
REPO = os.path.normpath(os.path.join(HERE, '..', '..', '..', '..'))
FUSE_ICONS = os.path.join(REPO, 'ui/designsystem/src/commonMain/kotlin/io/github/matiyaaa/fuse/ui/designsystem/icons/FuseIcons.kt')
GENERATOR = os.path.join(REPO, 'tools/icons/generate_icons.py')

# Fuse theme preset
INK = '#07080B'            # background
RAISED = '#1A1D25'         # surfaceRaised
ACCENT = '#FF6A3D'         # accent
ACCENT_LIGHT = '#FFB085'   # the spark's warm highlight (brand assets), lights the top of the strokes
LINE = '#F0582C'           # one colour for both GitHub themes (3.4:1 on white, 5.5:1 on #0d1117)

# file name, FuseIcons name, the concept (the SVG's title; the README gives each image its own alt text)
ICONS = [
    ('controller', 'Gamepad', 'Controller'),
    ('home', 'Home', 'Home screen'),
    ('library', 'Library', 'Library'),
    ('folders', 'FolderSearch', 'Game folders'),
    ('systems', 'Chip', 'Systems and emulators'),
    ('launch', 'Play', 'Launch'),
    ('artwork', 'Image', 'Artwork'),
    ('achievements', 'Trophy', 'Achievements'),
    ('cartridge', 'CloudDownload', 'Cartridge and RomM'),
    ('second-screen', 'DualScreen', 'Second screen'),
    ('phone-link', 'QrCode', 'Phone Link'),
    ('storage', 'HardDrive', 'Storage'),
    ('collections', 'LibraryBig', 'Collections'),
    ('interface', 'Sparkles', 'Interface'),
    ('themes', 'Palette', 'Themes'),
    ('accessibility', 'Accessibility', 'Accessibility'),
    ('privacy', 'ShieldCheck', 'Privacy'),
    ('read-only', 'Lock', 'Read-only'),
    ('android', 'Smartphone', 'Android'),
    ('linux', 'Monitor', 'Linux desktop'),
    ('free-software', 'Heart', 'Free software'),
]

# Badge geometry, in the 48 x 48 tile
TILE = 48
CORNER = 0.235       # corner radius as a fraction of the tile, as in docs/assets/brand/icon.svg
SMOOTHING = 0.6      # Fuse's continuous corner (SquircleShape default)
GLYPH = 26           # the 24 x 24 Lucide grid, drawn at this size in the middle of the tile
STROKE = 1.8         # in 24-grid units: the app's weight (LineIcon.kt), a little lighter than Lucide's 2
GLOW_STROKE = 3.2    # the blurred copy under the strokes
GLOW_BLUR = 1.6
GLOW_OPACITY = 0.55


def f(v):
    s = '%.2f' % v
    s = s.rstrip('0').rstrip('.') if '.' in s else s
    return '0' if s in ('-0', '') else s


def squircle_path(x, y, w, h, radius, smoothing=SMOOTHING):
    """SVG path data for Fuse's continuous-corner rectangle, the same construction as squirclePath in
    ui/designsystem (shape/SquircleShape.kt) and docs/assets/brand/source/geom.py."""
    half = min(w, h) / 2
    r = min(radius, half)
    pp = min((1 + smoothing) * r, half)
    s = min(max(pp / r - 1, 0), 1)
    arc_measure = 90 * (1 - s)
    arc_section = math.sin(math.radians(arc_measure / 2)) * r * math.sqrt(2)
    alpha = (90 - arc_measure) / 2
    p3p4 = r * math.tan(math.radians(alpha / 2))
    beta = 45 * s
    c = p3p4 * math.cos(math.radians(beta))
    d = c * math.tan(math.radians(beta))
    b = (pp - arc_section - c - d) / 3
    a = 2 * b
    P = lambda *v: ' '.join(f(q) for q in v)

    def arc_to(cx, cy, deg):
        return 'A' + P(r, r, 0, 0, 1, cx + r * math.cos(math.radians(deg)), cy + r * math.sin(math.radians(deg)))

    return ''.join([
        'M' + P(x + pp, y),
        'H' + f(x + w - pp),
        'C' + P(x + w - pp + a, y, x + w - pp + a + b, y, x + w - pp + a + b + c, y + d),
        arc_to(x + w - r, y + r, -90 + alpha + arc_measure),
        'C' + P(x + w, y + pp - a - b, x + w, y + pp - a, x + w, y + pp),
        'V' + f(y + h - pp),
        'C' + P(x + w, y + h - pp + a, x + w, y + h - pp + a + b, x + w - d, y + h - pp + a + b + c),
        arc_to(x + w - r, y + h - r, alpha + arc_measure),
        'C' + P(x + w - pp + a + b, y + h, x + w - pp + a, y + h, x + w - pp, y + h),
        'H' + f(x + pp),
        'C' + P(x + pp - a, y + h, x + pp - a - b, y + h, x + pp - a - b - c, y + h - d),
        arc_to(x + r, y + h - r, 90 + alpha + arc_measure),
        'C' + P(x, y + h - pp + a + b, x, y + h - pp + a, x, y + h - pp),
        'V' + f(y + pp),
        'C' + P(x, y + pp - a, x, y + pp - a - b, x + d, y + pp - a - b - c),
        arc_to(x + r, y + r, 180 + alpha + arc_measure),
        'C' + P(x + pp - a - b, y, x + pp - a, y, x + pp, y),
        'Z',
    ])


def lucide_names():
    """FuseIcons name -> Lucide file name, from the icon generator's own table."""
    spec = importlib.util.spec_from_file_location('generate_icons', GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.ICONS


def fuse_icon_paths():
    """FuseIcons name -> list of path data strings, as the app ships them."""
    src = open(FUSE_ICONS, encoding='utf-8').read()
    out = {}
    for m in re.finditer(r'val (\w+): ImageVector by lazy \{ lineIcon\("\w+", (.*)\) \}', src):
        out[m.group(1)] = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(2))
    return out


def paths_markup(paths):
    # One element per sub-path: several Lucide paths start with a relative "m", which would change
    # meaning if the strings were joined into one path.
    return ''.join(f'<path d="{d}"/>' for d in paths)


def comment(lucide):
    return f'<!-- Lucide "{lucide}" (ISC licence, see docs/assets/icons/README.md) -->'


def badge(name, label, lucide, paths):
    S = TILE
    r = S * CORNER
    o = (S - GLYPH) / 2
    k = GLYPH / 24
    tile = squircle_path(0, 0, S, S, r)
    edge = squircle_path(.25, .25, S - .5, S - .5, r - .25)
    glyph = paths_markup(paths)
    scale = '' if k == 1 else ' scale(' + ('%.4f' % k).rstrip('0') + ')'
    g = f'transform="translate({f(o)} {f(o)}){scale}"'
    defs = (
        f'<linearGradient id="t" x1="0" y1="0" x2="0" y2="{S}" gradientUnits="userSpaceOnUse">'
        f'<stop offset="0" stop-color="{RAISED}"/><stop offset="1" stop-color="{INK}"/></linearGradient>'
        # the room glow: warm light from the top right, as in the app icon
        f'<radialGradient id="r" cx="{f(S * .72)}" cy="{f(S * .24)}" r="{f(S * .8)}" gradientUnits="userSpaceOnUse">'
        f'<stop offset="0" stop-color="{ACCENT}" stop-opacity=".2"/><stop offset=".45" stop-color="{ACCENT}" stop-opacity=".06"/>'
        f'<stop offset="1" stop-color="{ACCENT}" stop-opacity="0"/></radialGradient>'
        f'<linearGradient id="e" x1="0" y1="0" x2="0" y2="{f(S / 2)}" gradientUnits="userSpaceOnUse">'
        '<stop offset="0" stop-color="#fff" stop-opacity=".22"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient>'
        # strokes lit from above: the spark's highlight fading into the accent
        '<linearGradient id="s" x1="0" y1="2" x2="0" y2="22" gradientUnits="userSpaceOnUse">'
        f'<stop offset="0" stop-color="{ACCENT_LIGHT}"/><stop offset=".5" stop-color="{ACCENT}"/></linearGradient>'
        f'<filter id="b" filterUnits="userSpaceOnUse" x="-4" y="-4" width="32" height="32"><feGaussianBlur stdDeviation="{f(GLOW_BLUR)}"/></filter>'
    )
    body = (
        f'<path d="{tile}" fill="url(#t)"/><path d="{tile}" fill="url(#r)"/>'
        f'<path d="{edge}" fill="none" stroke="url(#e)" stroke-width=".5"/>'
        f'<g {g} fill="none" stroke-linecap="round" stroke-linejoin="round">'
        f'<g stroke="{ACCENT}" stroke-width="{f(GLOW_STROKE)}" stroke-opacity="{f(GLOW_OPACITY)}" filter="url(#b)">{glyph}</g>'
        f'<g stroke="url(#s)" stroke-width="{f(STROKE)}">{glyph}</g></g>'
    )
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{S}" height="{S}" viewBox="0 0 {S} {S}" '
            f'role="img" aria-label="{label}">{comment(lucide)}<title>{label}</title><defs>{defs}</defs>{body}</svg>')


def line(name, label, lucide, paths):
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" '
            f'role="img" aria-label="{label}">{comment(lucide)}<title>{label}</title>'
            f'<g fill="none" stroke="{LINE}" stroke-width="{f(STROKE)}" stroke-linecap="round" stroke-linejoin="round">'
            f'{paths_markup(paths)}</g></svg>')


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as fh:
        fh.write(text + '\n')
    print(f'{os.path.relpath(path, OUT):28s} {len(text) + 1:6d} bytes')


def preview(out_dir, png, chromium=None):
    """A mock README feature grid (the way GitHub lays out a table) on both GitHub themes, then the
    badges at 32 px and the line icons at 20 px."""
    os.makedirs(out_dir, exist_ok=True)
    panels = []
    for bg, fg, muted, rule in (('#ffffff', '#1f2328', '#59636e', '#d1d9e0'), ('#0d1117', '#f0f6fc', '#9198a1', '#3d444d')):
        rows = ''
        for i in range(0, len(ICONS), 3):
            rows += '<tr>' + ''.join(
                f'<td><img src="file://{OUT}/{n}.svg" width="44" height="44"><br><b>{label}</b><br>'
                f'<sub>Lucide {key}, drawn on a Fuse tile.</sub></td>' for n, key, label in ICONS[i:i + 3]) + '</tr>'
        small = ''.join(f'<img src="file://{OUT}/{n}.svg" width="32" height="32">' for n, _, _ in ICONS)
        lines = ''.join(f'<img src="file://{OUT}/line/{n}.svg" width="20" height="20">' for n, _, _ in ICONS)
        panels.append(
            f'<section style="background:{bg};color:{fg};--m:{muted};--r:{rule}"><table>{rows}</table>'
            f'<p>{small}</p><p>{lines}</p></section>')
    html = ('<!doctype html><meta charset="utf-8"><style>body{margin:0;display:flex}'
            'section{width:880px;padding:24px 28px;font:14px/1.5 -apple-system,"Segoe UI","Noto Sans",Helvetica,Arial,sans-serif}'
            'table{border-collapse:collapse;width:100%}td{width:33%;vertical-align:top;padding:12px 14px;border:1px solid var(--r)}'
            'sub{color:var(--m);font-size:12px}p{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0 0}</style>'
            + ''.join(panels))
    page = os.path.join(out_dir, 'preview.html')
    write(page, html)
    if png:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(**({'executable_path': chromium} if chromium else {}))
            for scale in (1, 2):
                tab = browser.new_page(viewport={'width': 1760, 'height': 400}, device_scale_factor=scale)
                tab.goto('file://' + page)
                tab.wait_for_timeout(200)
                tab.screenshot(path=os.path.join(out_dir, f'preview@{scale}x.png'), full_page=True)
            browser.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--preview', metavar='DIR')
    ap.add_argument('--png', action='store_true')
    ap.add_argument('--chromium', metavar='PATH', help='Chromium executable, if Playwright has not installed its own')
    args = ap.parse_args()
    names = lucide_names()
    paths = fuse_icon_paths()
    for name, key, label in ICONS:
        write(os.path.join(OUT, f'{name}.svg'), badge(name, label, names[key], paths[key]))
        write(os.path.join(OUT, 'line', f'{name}.svg'), line(name, label, names[key], paths[key]))
    if args.preview:
        preview(args.preview, args.png, args.chromium)


if __name__ == '__main__':
    main()
