package io.github.matiyaaa.fuse.ui.designsystem.background

// Fusi's frames and the room's props, drawn pixel by pixel (generated from shapes, then tidied by hand).
// Legend: . clear, o outline, w fur, s fur shade, S ear edge, e eye, n nose, m mouth, t tongue,
// c blush, b bow, B bow shade, r pink, R deep pink, d door, k kibble, y kibble light.

internal object FusiFrames {
    val stand0 = PixelSprite(
        "..............................",
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "......oo.......owwBwwwBwwo....",
        "...ooowwo.....owwwwwwwwwwwo...",
        "..owwwwwo.....owwwwwwwwwwwo...",
        "..owwwwwo....owwwwwwwwwwwwwo..",
        ".owwwwwo.....oSSSweewweewSwo..",
        ".owwwwwooooooossSweewweeSsSo..",
        ".owwwoowwwwwwSssccwwnnwwccso..",
        "..ooowwwwwwwwSsssSwmwwmwSsso..",
        "...owwwwwwwwwSsssSwwmmwwSsso..",
        "...owwwwwwwwwSsssSssssssssso..",
        "...owwwwwwwwwwSsSwsssssooso...",
        "....osssssssssSsSsooooo..o....",
        "....owwswwssswwswwo...........",
        "....owwswwssswwswwo...........",
        "....owwowwooowwowwo...........",
        "....owwowwo.owwowwo...........",
        "....owwowwo.owwowwo...........",
        ".....oo.oo...oo.oo............",
        "..............................",
        "..............................",
    )

    val stand1 = PixelSprite(
        "..............................",
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        ".....ooo.......owwBwwwBwwo....",
        "....owwwo.....owwwwwwwwwwwo...",
        "...owwwwwo....owwwwwwwwwwwo...",
        "..owwwwwwo...owwwwwwwwwwwwwo..",
        ".owwwwwwo....oSSSweewweewSwo..",
        ".owwwwwooooooossSweewweeSsSo..",
        "..owwoowwwwwwSssccwwnnwwccso..",
        "...oowwwwwwwwSsssSwmwwmwSsso..",
        "...owwwwwwwwwSsssSwwmmwwSsso..",
        "...owwwwwwwwwSsssSssssssssso..",
        "...owwwwwwwwwwSsSwsssssooso...",
        "....osssssssssSsSsooooo..o....",
        "....owwswwssswwswwo...........",
        "....owwswwssswwswwo...........",
        "....owwowwooowwowwo...........",
        "....owwowwo.owwowwo...........",
        "....owwowwo.owwowwo...........",
        ".....oo.oo...oo.oo............",
        "..............................",
        "..............................",
    )

    val blink = PixelSprite(
        "..............................",
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "......oo.......owwBwwwBwwo....",
        "...ooowwo.....owwwwwwwwwwwo...",
        "..owwwwwo.....owwwwwwwwwwwo...",
        "..owwwwwo....owwwwwwwwwwwwwo..",
        ".owwwwwo.....oSSSwwwwwwwwSwo..",
        ".owwwwwooooooossSweewweeSsSo..",
        ".owwwoowwwwwwSssccwwnnwwccso..",
        "..ooowwwwwwwwSsssSwmwwmwSsso..",
        "...owwwwwwwwwSsssSwwmmwwSsso..",
        "...owwwwwwwwwSsssSssssssssso..",
        "...owwwwwwwwwwSsSwsssssooso...",
        "....osssssssssSsSsooooo..o....",
        "....owwswwssswwswwo...........",
        "....owwswwssswwswwo...........",
        "....owwowwooowwowwo...........",
        "....owwowwo.owwowwo...........",
        "....owwowwo.owwowwo...........",
        ".....oo.oo...oo.oo............",
        "..............................",
        "..............................",
    )

    val walk0 = PixelSprite(
        "..............................",
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "......oo.......owwBwwwBwwo....",
        "...ooowwo.....owwwwwwwwwwwo...",
        "..owwwwwo.....owwwwwwwwwwwo...",
        "..owwwwwo....owwwwwwwwwwwwwo..",
        ".owwwwwo.....oSSSweewweewSwo..",
        ".owwwwwooooooossSweewweeSsSo..",
        ".owwwoowwwwwwSssccwwnnwwccso..",
        "..ooowwwwwwwwSsssSwmwwmwSsso..",
        "...owwwwwwwwwSsssSwwttwwSsso..",
        "...owwwwwwwwwSsssSssssssssso..",
        "...owwwwwwwwwwSsSwsssssooso...",
        "....osssssssssssSsooooo..o....",
        "....owwsswwswwsswwo...........",
        "....owwsowwswwoswwo...........",
        "....owwoowwowwoowwo...........",
        "....owwoowwowwoowwo...........",
        ".....oo.owwowwo.oo............",
        ".........oo.oo................",
        "..............................",
        "..............................",
    )

    val walk1 = PixelSprite(
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "......oo.......owwBwwwBwwo....",
        "...ooowwo.....owwwwwwwwwwwo...",
        "..owwwwwo.....owwwwwwwwwwwo...",
        "..owwwwwo....owwwwwwwwwwwwwo..",
        ".owwwwwo.....oSSSweewweewSwo..",
        ".owwwwwooooooossSweewweeSsSo..",
        ".owwwoowwwwwwSssccwwnnwwccso..",
        "..ooowwwwwwwwSsssSwmwwmwSsso..",
        "...owwwwwwwwwSsssSwwttwwSsso..",
        "...owwwwwwwwwSsssSssssssssso..",
        "...owwwwwwwwwwSsSwsssssooso...",
        "....osssssssssSsssooooo..o....",
        "...owwsswwssswwsswwo..........",
        "...owwoswwssswwsowwo..........",
        "...owwoowwooowwoowwo..........",
        "...owwoowwo.owwoowwo..........",
        "...owwo.oo...oo.owwo..........",
        "....oo...........oo...........",
        "..............................",
        "..............................",
        "..............................",
    )

    val run0 = PixelSprite(
        "..............................",
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "...............owwBwwwBwwo....",
        "..............owwwwwwwwwwwo...",
        "..oooo.......oowwwwwwwwwwwo...",
        ".owwwwo.....ossSwwwwwwwwwwwo..",
        "owwwwwo....ossssSweewweeSSwo..",
        "wwwwwwoooooossssSweewweessSo..",
        "wwwwwowwwwwwSsssccwwnnwSccso..",
        "wwwwwwwwwwwwSsssSwwmwwmwsso...",
        "ooowwwwwwwwwwSSSwwwwttwwSso...",
        "..owwwwwwwwwwwwwssssssssso....",
        "..owwwwwwwwwwwwwwwsssssoo.....",
        "...ossssssssssssssooooo.......",
        "....osswwwwsswwwwo............",
        "....osowwwwsswwwwo............",
        ".....oowwwwoowwwwo............",
        "......owwwwoowwwwo............",
        ".......oowwoowwoo.............",
        ".........oo..oo...............",
        "..............................",
        "..............................",
    )

    val run1 = PixelSprite(
        "..............................",
        "..................bbobb.......",
        "................oobbBbboo.....",
        "...............owwBwwwBwwo....",
        "..............owwwwwwwwwwwo...",
        "..oooo.......oowwwwwwwwwwwo...",
        ".owwwwo.....ossSwwwwwwwwwwwo..",
        "owwwwwo....ossssSweewweeSSwo..",
        "wwwwwwoooooossssSweewweessSo..",
        "wwwwwowwwwwwSsssccwwnnwSccso..",
        "wwwwwwwwwwwwSsssSwwmwwmwsso...",
        "ooowwwwwwwwwwSSSwwwwttwwSso...",
        "..owwwwwwwwwwwwwssssssssso....",
        "..owwwwwwwwwwwwwwwsssssoo.....",
        "..oossssssssssssssooooo.......",
        ".owwowwsssssssssswwowwo.......",
        ".owwowwsosssssosowwowwo.......",
        ".owwowwo.ooooo.oowwowwo.......",
        ".owwowwo........owwowwo.......",
        "..ooowwo........owwooo........",
        ".....oo..........oo...........",
        "..............................",
        "..............................",
        "..............................",
    )

    val sit0 = PixelSprite(
        "..............................",
        "................bbobb.........",
        "..............oobbBbbo........",
        ".............owwBwwwBwo.......",
        "............owwwwwwwwwwo......",
        "...........owwwwwwwwwwwwo.....",
        "...........owwwwwwwwwwwwo.....",
        "..........owSSweewwweeSSwo....",
        "..........oSssSeewwweeSSwo....",
        "..........ossccwwnnwwSccSo....",
        ".........owSssswmwwmwSssso....",
        ".........owSssswwmmwwSssso....",
        "......ooowwSsssssssssssso.....",
        "..oooowwwwwSssSwssssoosso.....",
        ".owwwwwwwwwwSSwwwwoo..oo......",
        ".osssssssssssssssso...........",
        ".ossssssssssssssso............",
        "..osssssssssswwswwo...........",
        "..osssssssssswwswwo...........",
        "...oooossssoowwowwo...........",
        ".......oooo.owwowwo...........",
        ".............oo.oo............",
        "..............................",
        "..............................",
    )

    val sit1 = PixelSprite(
        "..............................",
        "................bbobb.........",
        "..............oobbBbbo........",
        ".............owwBwwwBwo.......",
        "............owwwwwwwwwwo......",
        "...........owwwwwwwwwwwwo.....",
        "...........owwwwwwwwwwwwo.....",
        "..........owSSweewwweeSSwo....",
        "..........oSssSeewwweeSSwo....",
        "..........ossccwwnnwwSccSo....",
        ".........owSssswmwwmwSssso....",
        ".........owSssswwmmwwSssso....",
        "..ooo.ooowwSsssssssssssso.....",
        ".owwwowwwwwSssSwssssoosso.....",
        ".owwwwwwwwwwSSwwwwoo..oo......",
        ".osssssssssssssssso...........",
        "..osssssssssssssso............",
        "..osssssssssswwswwo...........",
        "..osssssssssswwswwo...........",
        "...oooossssoowwowwo...........",
        ".......oooo.owwowwo...........",
        ".............oo.oo............",
        "..............................",
        "..............................",
    )

    val sitBlink = PixelSprite(
        "..............................",
        "................bbobb.........",
        "..............oobbBbbo........",
        ".............owwBwwwBwo.......",
        "............owwwwwwwwwwo......",
        "...........owwwwwwwwwwwwo.....",
        "...........owwwwwwwwwwwwo.....",
        "..........owSSwwwwwwwwSSwo....",
        "..........oSssSeewwweeSSwo....",
        "..........ossccwwnnwwSccSo....",
        ".........owSssswmwwmwSssso....",
        ".........owSssswwmmwwSssso....",
        "......ooowwSsssssssssssso.....",
        "..oooowwwwwSssSwssssoosso.....",
        ".owwwwwwwwwwSSwwwwoo..oo......",
        ".osssssssssssssssso...........",
        ".ossssssssssssssso............",
        "..osssssssssswwswwo...........",
        "..osssssssssswwswwo...........",
        "...oooossssoowwowwo...........",
        ".......oooo.owwowwo...........",
        ".............oo.oo............",
        "..............................",
        "..............................",
    )

    val sleep = PixelSprite(
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "................obbobbo.......",
        "...............owbbBbbwo......",
        "..............owwBwwwBwwo.....",
        ".............owwwwwwwwwwwo....",
        "........ooooowwwwwwwwwwwwwo...",
        "..oooooowwwwwwwwwwwwwwwwwwo...",
        ".owwwwwwwwwwwwSSeewwweewSSo...",
        "owwwwwwwwwwwwSccSwwnnwwccso...",
        "owwwwwwwwwwwSsssSwwwwwwSsso...",
        "owwwwwwwwwwwSsssSwwwwwwSsso...",
        "osssossssssssssssssssssssso...",
        "osso.oossssssssssssssssooo....",
        ".oo...osososososooooooo.......",
        ".......o.o.o.o.o..............",
        "..............................",
        "..............................",
    )

    val sniff0 = PixelSprite(
        "..............................",
        "..............................",
        "..............................",
        "......o.......................",
        "....oowo......................",
        "...owwwwo.....................",
        "..owwwwwo.........obbobbo.....",
        ".owwwwwo.........owbbBbbwo....",
        ".owwwwwo........owwBwwwBwwo...",
        ".owwwooooooooooowwwwwwwwwwwo..",
        "..owooowwwwwwwwwwwwwwwwwwwwwo.",
        "...oowwwwwwwwwwwwweewwweewwwo.",
        "...owwwwwwwwwwwSSSeewwweewSwo.",
        "...owwwwwwwwwwwSccwwwnnwwccSo.",
        "...owwwwwwwwwwSsssSwmwwmwSsso.",
        "....osssssssssSsssSwwmmwwSsso.",
        "....owwswwssswwssssssssssssso.",
        "....owwswwssswwSsssssssssoso..",
        "....owwowwooowwoSSooooooo.o...",
        "....owwowwo.owwowwo...........",
        "....owwowwo.owwowwo...........",
        ".....oo.oo...oo.oo............",
        "..............................",
        "..............................",
    )

    val sniff1 = PixelSprite(
        "..............................",
        "..............................",
        "..............................",
        "....ooo.......................",
        "...owwwo......................",
        "..owwwwwo.....................",
        "..owwwwwo.........obbobbo.....",
        ".owwwwwo.........owbbBbbwo....",
        ".owwwwo.........owwBwwwBwwo...",
        ".owwwo.ooooooooowwwwwwwwwwwo..",
        "..owooowwwwwwwwwwwwwwwwwwwwwo.",
        "...oowwwwwwwwwwwwweewwweewwwo.",
        "...owwwwwwwwwwwSSSeewwweewSwo.",
        "...owwwwwwwwwwwSccwwwnnwwccSo.",
        "...owwwwwwwwwwSsssSwmwwmwSsso.",
        "....osssssssssSsssSwwmmwwSsso.",
        "....owwswwssswwssssssssssssso.",
        "....owwswwssswwSsssssssssoso..",
        "....owwowwooowwoSSooooooo.o...",
        "....owwowwo.owwowwo...........",
        "....owwowwo.owwowwo...........",
        ".....oo.oo...oo.oo............",
        "..............................",
        "..............................",
    )

    val jump = PixelSprite(
        "..................bbobb.......",
        "................oobbBbboo.....",
        "......oo.......owwBwwwBwwo....",
        "...ooowwo.....owwwwwwwwwwwo...",
        "..owwwwwo....osSwwwwwwwwwwo...",
        "..owwwwwo...osssSwwwwwwwSSwo..",
        ".owwwwwo....osssSweewweeSsSo..",
        ".owwwwwoooooosssSweewweeSsso..",
        ".owwwoowwwwwwSssccwwnnwwccso..",
        "..ooowwwwwwwwSssSwwmwwmwSSso..",
        "...owwwwwwwwwwSSwwwwttwwwwo...",
        "...owwwwwwwwwwwwssssssssso....",
        "...owwwwwwwwwwwwwwsssssoo.....",
        "....osssssssssssssooooo.......",
        ".....owwwwsssswwwwo...........",
        ".....owwwwsssswwwwo...........",
        ".....owwwwoooowwwwo...........",
        "......oooo....oooo............",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
        "..............................",
    )

    val house = PixelSprite(
        "........oo........",
        ".......orro.......",
        "......orrrro......",
        ".....orrrrrro.....",
        "....orrrrrrrro....",
        "...orrrrrrrrrro...",
        "..orrrrrrrrrrrro..",
        ".oRRRRRRRRRRRRRRo.",
        "oooooooooooooooooo",
        "..owwwwwwwwwwwwo..",
        "..owwwwoooowwwwo..",
        "..owwwoddddowwwo..",
        "..owwwoddddowwwo..",
        "..owwsoddddoswwo..",
        "..osssoddddossso..",
        "..oooooooooooooo..",
    )

    val ball = PixelSprite(
        ".oooo.",
        "orrrro",
        "owwwwo",
        "orrrro",
        "oRRRRo",
        ".oooo.",
    )

    val bowl = PixelSprite(
        ".kyky.kk.",
        "orrrrrrro",
        ".oRRRRRo.",
        "..ooooo..",
    )

    val heart = PixelSprite(
        ".rr.rr.",
        "rrrrrrr",
        "rrrrrrr",
        ".rrrrr.",
        "..rrr..",
        "...r...",
    )

    val z = PixelSprite(
        "oooo",
        "..o.",
        ".o..",
        "oooo",
    )
}
